server:
  port: 8084
#spring:
#  data:
#    mongodb:
#      uri: mongodb://${email_db_user:root}:${email_db_pwd:root}@127.0.0.1:27017/TestDatabase?authSource=admin
#      authentication-database: admin

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:tododb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

